root: "/home/marcus.hughes/running_test/"
input_drop: "dropzone/"
file_version: "0.0.1"

launcher:
  max_seconds_waiting: 100
  escalated_priority: 100
  max_flows_running: 30

levels:
  level0_process_flow:
    priority:
      initial: 5
      seconds: [ 30, 120, 600 ]
      escalation: [ 10, 20, 30 ]
    schedule:
      latency: 3
      window_duration_seconds: 3
      cron_rule: "******"
    options:
      num_quads: 100

  level1_process_flow:
    priority:
      initial: 6
      seconds: [ 30, 120, 600 ]
      escalation: [ 11, 21, 31 ]
    schedule:
      latency: 3
      window_duration_seconds: 3
      cron_rule: "******"
    options:

  level2_process_flow:
    priority:
      initial: 7
      seconds: [ 30, 120, 600 ]
      escalation: [ 12, 22, 32 ]
    schedule:
      latency: 3
      window_duration_seconds: 3
      cron_rule: "******"
    options:
