root: "/Users/mhughes/data/punch_simulation/"
tlm_directory: "/Users/mhughes/data/punch_simulation/RAW_CCSDS_DATA/"
file_version: "1"
bucket_name: "output_bucket_name"

plate_scale:
  1: 0.02444444444
  2: 0.02444444444
  3: 0.02444444444
  4: 0.008333333333

quality_check:
  mean_low: 0
  mean_high: 65000

scheduler:
  max_start: 10

control:
  launcher:
    description: "Kick off new flows for processing."
    max_flows_running: 50
    max_flows_to_launch_at_once: 20
  health_monitor:
    description: "Monitor the health of the pipeline."

flows:
#  level0:
#    description: "Creates Level 0 files from raw packets."
#    tags: ["L0"]
#    concurrency_limit: 1
#    priority:
#      initial: 5
#      seconds: [ 30, 120, 600 ]
#      escalation: [ 10, 20, 30 ]
#    schedule: "*/30 * * * *"
#    options:

  level1:
    description: "Creates Level 1 files."
    tags: ["L1"]
    priority:
      initial: 6
      seconds: [ 30, 120, 600 ]
      escalation: [ 11, 21, 31 ]
    schedule: "* * * * *"
    options:

  level2:
    description: "Creates Level 2 files."
    tags: [ "L2" ]
    priority:
      initial: 1000
      seconds: [ 3000, 12000, 60000 ]
      escalation: [ 1000, 1000, 1000 ]
    schedule: "* * * * *"
    options:

  levelq:
    description: "Creates Level Q CTM and CNN data files."
    tags: [ "LQ" ]
    priority:
      initial: 1000
      seconds: [ 3000, 12000, 60000 ]
      escalation: [ 1000, 1000, 1000 ]
    schedule: "* * * * *"
    options:

  levelq_upload:
    description: "Uploads Level Q files."
    tags: [ "LQ" ]
    priority:
      initial: 1000
      seconds: [ 3000, 12000, 60000 ]
      escalation: [ 1000, 1000, 1000 ]
    schedule: "* * * * *"
    options:

  levelq_CFM:
    description: "Makes Level Q CFM files."
    tags: [ "LQ" ]
    priority:
      initial: 1000
      seconds: [ 3000, 12000, 60000 ]
      escalation: [ 1000, 1000, 1000 ]
    schedule: "* * * * *"
    options:

  levelq_CFN:
    description: "Makes Level Q CFN files."
    tags: [ "LQ" ]
    priority:
      initial: 1000
      seconds: [ 3000, 12000, 60000 ]
      escalation: [ 1000, 1000, 1000 ]
    schedule: "* * * * *"
    options:

  L3_PTM:
    description: "Creates Level 3 PTM files."
    tags: [ "L3" ]
    priority:
      initial: 10000
      seconds: [1]
      escalation: [10000]
    schedule: "* * * * *"
    options:

  L3_PIM:
    description: "Creates Level 3 PIM files."
    tags: [ "L3" ]
    priority:
      initial: 10000
      seconds: [1]
      escalation: [10000]
    schedule: "* * * * *"
    options:

  f_corona:
    description: "Creates Level 3 f corona model files."
    tags: [ "L3" ]
    priority:
      initial: 10000
      seconds: [1]
      escalation: [10000]
    schedule: "* * * * *"
    options:

  starfield:
    description: "Creates Level 3 starfield files."
    tags: [ "L3" ]
    priority:
      initial: 10000
      seconds: [1]
      escalation: [10000]
    schedule: "* * * * *"
    options:

  visualize:
    description: "Creates quicklook movies."
    tags: [ "LQ" ]
    priority:
      initial: 10
      seconds: [60*60*24]
      escalation: [1000]
    schedule: "0 0 * * *"
    options:

  simpunch:
    description: "Runs simpunch."
    tags: [ "sim" ]
    priority:
      initial: 1
      seconds: [1]
      escalation: [1]
    schedule: "0 */8 * * *"
    options:
      gamera_files_dir: "/Users/mhughes/data/punch_simulation/synthetic_cme/"
      out_dir: "/Users/mhughes/data/punch_simulation/outputs/"
      simulation_start: "2025-03-21T08:00:00"
      simulation_cadence_minutes: 4.0
      backward_psf_model_path: "/Users/mhughes/data/punch_simulation/inputs/synthetic_backward_psf.fits"
      wfi_quartic_backward_model_path: "/Users/mhughes/data/punch_simulation/inputs/wfi_quartic_backward_coeffs.fits"
      nfi_quartic_backward_model_path: "/Users/mhughes/data/punch_simulation/inputs/nfi_quartic_backward_coeffs.fits"
      transient_probability: 0.0
      shift_pointing: false
