root: "/Users/jhughes/Desktop/d0/"
input_drop: "dropzone/"
tlm_directory: "dropzone/"
file_version: "1"

plate_scale:
  1: 88 / 3600
  2: 88 / 3600
  3: 88 / 3600
  4: 30 / 3600

quality_check:
  mean_low: 0
  mean_high: 65000

scheduler:
  max_start: 10

control:
  launcher:
    schedule: "* * * * *"
    max_flows_running: 25

flows:
  generate_flow:
    priority:
      initial: 1
      seconds: [1]
      escalation: [1]
    schedule: "* * * * *"
    options:
      gamera_directory: "/home/jmbhughes/data/synthetic_cme/"
      output_directory: "/home/jmbhughes/data/synthetic_cme/"
      forward_psf_model_path: "/home/jmbhughes/data/simpunch/inputs/synthetic_forward_psf.fits"
      backward_psf_model_path: "/home/jmbhughes/data/simpunch/inputs/synthetic_backward_psf.fits"
      wfi_quartic_backward_model_path: "/home/jmbhughes/data/simpunch/inputs/wfi_quartic_backward_coeffs.fits"
      nfi_quartic_backward_model_path: "/home/jmbhughes/data/simpunch/inputs/nfi_quartic_backward_coeffs.fits"
      wfi_quartic_model_path: "/home/jmbhughes/data/simpunch/inputs/wfi_quartic_coeffs.fits"
      nfi_quartic_model_path: "/home/jmbhughes/data/simpunch/inputs/nfi_quartic_coeffs.fits"
      transient_probability: 0.0
      shift_pointing: false
