[tool.ruff]
target-version = 'py38'
exclude = ['tests', 'scripts', 'docs']
line-length=120

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"*/tests/*" = ['S101']

[tool.isort]
balanced_wrapping = true
default_section = "THIRDPARTY"
include_trailing_comma = true
known_compatibility = "future"
known_first_party = "punchbowl"
length_sort = false
length_sort_sections = "stdlib"
line_length = 120
multi_line_output = 3
no_lines_before = "LOCALFOLDER"
sections = "FUTURE, COMPATIBILITY, STDLIB, THIRDPARTY, FIRSTPARTY, LOCALFOLDER"

[tool.pytest.ini_options]
markers = [
    "prefect_test: a test that integrates with Prefect",
    "regression: a regression test, likely slow",
]
